import{a as L,i as q,S as w}from"./assets/vendor-Qob_5Ba8.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const o of document.querySelectorAll('link[rel="modulepreload"]'))n(o);new MutationObserver(o=>{for(const r of o)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&n(i)}).observe(document,{childList:!0,subtree:!0});function s(o){const r={};return o.integrity&&(r.integrity=o.integrity),o.referrerPolicy&&(r.referrerPolicy=o.referrerPolicy),o.crossOrigin==="use-credentials"?r.credentials="include":o.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(o){if(o.ep)return;o.ep=!0;const r=s(o);fetch(o.href,r)}})();const S="46111886-e1974f40af7d3aa808257f9c9",v="https://pixabay.com/api/",y=async(e,t=1)=>{try{return(await L.get(v,{params:{key:S,q:encodeURIComponent(e),page:t,per_page:15,image_type:"photo",orientation:"horizontal",safesearch:!0}})).data}catch(s){throw console.error("Error fetching images:",s),s}},f=e=>{const t=document.querySelector(".gallery"),s=e.map(({webformatURL:n,largeImageURL:o,tags:r,likes:i,views:p,comments:h,downloads:b})=>`
            <li class="gallery-item">
                <a href="${o}" class="gallery-link">
                    <img class="gallery-image" src="${n}" alt="${r}" loading="lazy" />
                    <div class="info">
                        <p class="info-item"><b>Likes:</b> ${i}</p>
                        <p class="info-item"><b>Views:</b> ${p}</p>
                        <p class="info-item"><b>Comments:</b> ${h}</p>
                        <p class="info-item"><b>Downloads:</b> ${b}</p>
                    </div>
                </a>
            </li>
        `).join("");t.insertAdjacentHTML("beforeend",s)},a=(e,t="topRight")=>{q.error({title:"Error",message:e,position:t,timeout:2e3,backgroundColor:"#EF4040"}),setTimeout(()=>{errorMessage.classList.add("fade-out"),setTimeout(()=>{errorMessage.remove()},500)},3e3)},M=()=>{const e=document.querySelector(".gallery");e.innerHTML=""},P=()=>{const e=document.querySelector("#loadmore");e.style.display="block"},u=()=>{const e=document.querySelector("#loadmore");e.style.display="none"},R=document.querySelector("#searchform"),E=document.querySelector("#loadmore"),d=document.querySelector("#loader"),g=new w(".gallery a");let c="",l=1;const m=15;R.addEventListener("submit",async e=>{if(e.preventDefault(),c=e.target.elements.query.value.trim(),l=1,M(),!c){a("Please enter a search query","topRight");return}d.style.display="block";try{const t=await y(c,l);f(t.hits),g.refresh(),t.totalHits>0?t.totalHits>15?P():(u(),a("We're sorry, but you've reached the end of search results.","bottomRight")):(u(),a("No images found","topRight"))}catch{a("Failed to load images. Please try again later.","topRight")}finally{d.style.display="none"}});E.addEventListener("click",async()=>{l+=1,d.style.display="block";try{const e=await y(c,l);f(e.hits),g.refresh();const t=document.querySelector(".gallery-item");if(t){const{height:s}=t.getBoundingClientRect();window.scrollBy({top:s*2,behavior:"smooth"})}(e.hits.length<m||l*m>=e.totalHits)&&(u(),a("We're sorry, but you've reached the end of search results.","bottomRight"))}catch{a("Failed to load more images. Please try again later.","topRight")}finally{d.style.display="none"}});
//# sourceMappingURL=index.js.map
